name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Автоматическая сборка при создании тега (например v1.0.0)
  workflow_dispatch:  # Ручной запуск через Actions вкладку

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write  # Необходимо для публикации в GHCR

    steps:
      # Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch  # Для веток (например: main)
            type=ref,event=tag     # Для тегов (например: v1.0.0)
            type=sha               # Тег с SHA коммита

            
      # Логин в GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Автоматически использует логин GitHub
          password: ${{ secrets.GITHUB_TOKEN }}  # Токен создается автоматически
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container 
          install: true             
          
      # Сборка и публикация образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Где искать Dockerfile (корень репозитория)
          push: true  # Публиковать образ после сборки
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.tags  }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
